use strict;
use warnings;

use Digest::SHA qw(sha256_hex);
use B qw(svref_2object SVp_IOK SVp_NOK);
use File::Basename qw(dirname);
use File::Spec;
use JSON qw(decode_json);
use Test::More;

my $root = File::Spec->rel2abs(File::Spec->catdir(dirname(__FILE__), '..'));
my $fixture = File::Spec->catfile($root, 't', 'fixtures', 'fullStatus-flex-observed.json');

open my $fh, '<:raw', $fixture or die "Cannot read $fixture: $!";
local $/;
my $bytes = <$fh>;
close $fh;

is(sha256_hex($bytes), 'ca8f70cd954ebd70684744386660b80b4ce6a2cc0a5ab7751c27b59676b09d33',
    'observed fixture retains the published pretty-printed SHA-256');

my $data = eval { decode_json($bytes) };
ok(!$@ && ref($data) eq 'HASH', 'observed fixture is valid JSON');
is($data->{type}, 'fullStatus', 'fixture is a fullStatus message');
ok(exists $data->{partial} && !$data->{partial}, 'observed fullStatus is explicitly non-partial');
ok(ref($data->{status}) eq 'HASH', 'fixture contains a status object');

my %expected_type = (
    'abm' => 'string',
    'acl' => 'null',
    'acs' => 'number',
    'acu' => 'null',
    'acui' => 'null',
    'adi' => 'boolean',
    'ado' => 'null',
    'al1' => 'number',
    'al2' => 'number',
    'al3' => 'number',
    'al4' => 'number',
    'al5' => 'number',
    'alw' => 'boolean',
    'alwt' => 'number',
    'ama' => 'number',
    'amp' => 'number',
    'amt' => 'number',
    'ana' => 'boolean',
    'apd' => 'object',
    'app' => 'boolean',
    'art' => 'string',
    'arv' => 'string',
    'asc' => 'boolean',
    'aup' => 'number',
    'aus' => 'boolean',
    'aut' => 'null',
    'authhash' => 'string',
    'avgfhz' => 'number',
    'awc' => 'number',
    'awcp' => 'object',
    'awp' => 'number',
    'awpl' => 'object',
    'bam' => 'number',
    'bpwm0' => 'number',
    'bpwm1' => 'number',
    'bpwm2' => 'number',
    'bpwm3' => 'number',
    'c0e' => 'number',
    'c0i' => 'boolean',
    'c0n' => 'string',
    'c1e' => 'number',
    'c1i' => 'boolean',
    'c1n' => 'string',
    'c2e' => 'number',
    'c2i' => 'boolean',
    'c2n' => 'string',
    'c3e' => 'number',
    'c3i' => 'boolean',
    'c3n' => 'string',
    'c4e' => 'number',
    'c4i' => 'boolean',
    'c4n' => 'string',
    'c5e' => 'number',
    'c5i' => 'boolean',
    'c5n' => 'string',
    'c6e' => 'number',
    'c6i' => 'boolean',
    'c6n' => 'string',
    'c7e' => 'number',
    'c7i' => 'boolean',
    'c7n' => 'string',
    'c8e' => 'number',
    'c8i' => 'boolean',
    'c8n' => 'string',
    'c9e' => 'number',
    'c9i' => 'boolean',
    'c9n' => 'string',
    'cae' => 'boolean',
    'cak' => 'string',
    'car' => 'number',
    'cbdt' => 'number',
    'cble' => 'boolean',
    'cbm' => 'string',
    'cbtt' => 'number',
    'cc4' => 'object',
    'cc42l' => 'boolean',
    'cc4ae' => 'array',
    'cc4ap' => 'array',
    'cc4ca' => 'boolean',
    'cc4cd' => 'boolean',
    'cc4cs' => 'number',
    'cc4dc' => 'number',
    'cc4fm' => 'array',
    'cc4fu' => 'boolean',
    'cc4i1' => 'boolean',
    'cc4is' => 'number',
    'cc4lc' => 'boolean',
    'cc4ld' => 'boolean',
    'cc4ls' => 'number',
    'cc4lt' => 'number',
    'cc4nl' => 'boolean',
    'cc4pm' => 'array',
    'cc4pp' => 'number',
    'cc4rc' => 'array',
    'cc4re' => 'array',
    'cc4rf' => 'boolean',
    'cc4rp' => 'array',
    'cc4rv' => 'array',
    'cc4sf' => 'boolean',
    'cc4sp' => 'number',
    'cc4ss' => 'number',
    'cc4st' => 'number',
    'cc4sv' => 'boolean',
    'cc4tl' => 'number',
    'cc4tm' => 'boolean',
    'cc4tt' => 'boolean',
    'cc4tv' => 'boolean',
    'cc4vm' => 'number',
    'cc4vr' => 'boolean',
    'cc4vx' => 'number',
    'cca' => 'boolean',
    'cce' => 'object',
    'cch' => 'string',
    'cci' => 'object',
    'cco' => 'number',
    'ccrv' => 'string',
    'ccsm' => 'null',
    'ccu' => 'null',
    'ccw' => 'null',
    'cdci' => 'number',
    'cdi' => 'object',
    'cert' => 'number',
    'cfi' => 'string',
    'cgc' => 'boolean',
    'chr' => 'boolean',
    'cid' => 'string',
    'cle' => 'null',
    'clea' => 'null',
    'cll' => 'object',
    'clp' => 'array',
    'cnt' => 'number',
    'cot' => 'null',
    'cpe' => 'boolean',
    'cpi' => 'number',
    'cpr' => 'boolean',
    'cpt' => 'number',
    'csd' => 'boolean',
    'ct' => 'string',
    'cup' => 'number',
    'cwc' => 'string',
    'cwe' => 'boolean',
    'cws' => 'boolean',
    'cwsc' => 'boolean',
    'cwsca' => 'number',
    'cy' => 'string',
    'data' => 'string',
    'dbm' => 'string',
    'dci' => 'number',
    'dco' => 'boolean',
    'deb' => 'boolean',
    'demo' => 'boolean',
    'dfam' => 'string',
    'di1' => 'boolean',
    'die' => 'boolean',
    'dii' => 'boolean',
    'din' => 'number',
    'dll' => 'string',
    'dns' => 'object',
    'dwo' => 'null',
    'ebe' => 'boolean',
    'ebo' => 'boolean',
    'ebt' => 'number',
    'ebv' => 'boolean',
    'ee' => 'boolean',
    'eis' => 'null',
    'emx' => 'number',
    'ens' => 'string',
    'err' => 'number',
    'esd0' => 'string',
    'esd1' => 'string',
    'esd2' => 'string',
    'esg' => 'string',
    'esi' => 'string',
    'esk' => 'boolean',
    'ess' => 'string',
    'eto' => 'number',
    'eto_mid' => 'number',
    'etop' => 'number',
    'eusd' => 'boolean',
    'euse' => 'boolean',
    'evt' => 'null',
    'exp' => 'boolean',
    'facacs' => 'number',
    'faccak' => 'string',
    'facice' => 'boolean',
    'facpass' => 'boolean',
    'facwak' => 'boolean',
    'fam' => 'number',
    'fap' => 'boolean',
    'fbuf_age' => 'number',
    'fbuf_akkuMode' => 'number',
    'fbuf_akkuSOC' => 'number',
    'fbuf_ohmpilotState' => 'null',
    'fbuf_ohmpilotTemperature' => 'null',
    'fbuf_pAcTotal' => 'null',
    'fbuf_pAkku' => 'number',
    'fbuf_pGrid' => 'number',
    'fbuf_pPv' => 'number',
    'fcc' => 'boolean',
    'fck' => 'boolean',
    'fdt' => 'number',
    'ferm' => 'number',
    'ffna' => 'string',
    'fhi' => 'boolean',
    'fhz' => 'number',
    'fhzo' => 'null',
    'fi23' => 'boolean',
    'fio23' => 'number',
    'fit' => 'number',
    'fldb' => 'boolean',
    'fml' => 'string',
    'fmmp' => 'number',
    'fmt' => 'number',
    'fna' => 'string',
    'fntp' => 'null',
    'forsch' => 'boolean',
    'fot' => 'number',
    'frc' => 'number',
    'frci' => 'boolean',
    'fre' => 'boolean',
    'frm' => 'number',
    'frt' => 'number',
    'fsp' => 'boolean',
    'fsptws' => 'null',
    'fst' => 'number',
    'fte' => 'number',
    'ftlf' => 'boolean',
    'ftls' => 'null',
    'ftt' => 'number',
    'ful' => 'boolean',
    'fup' => 'boolean',
    'fuzz' => 'array',
    'fwan' => 'string',
    'fwc' => 'string',
    'fwv' => 'string',
    'fzf' => 'boolean',
    'gme' => 'boolean',
    'gmk' => 'string',
    'gmtr' => 'number',
    'grp' => 'string',
    'gsa' => 'null',
    'host' => 'string',
    'hsa' => 'boolean',
    'hsta' => 'string',
    'hste' => 'string',
    'hsts' => 'string',
    'hws' => 'boolean',
    'ice' => 'boolean',
    'ido' => 'null',
    'imd' => 'boolean',
    'imi' => 'string',
    'immr' => 'number',
    'imp' => 'string',
    'ims' => 'string',
    'imse' => 'boolean',
    'ipw' => 'string',
    'iri' => 'number',
    'irs' => 'boolean',
    'isgo' => 'boolean',
    'isip' => 'boolean',
    'isml' => 'boolean',
    'iuse' => 'boolean',
    'la1' => 'number',
    'la3' => 'number',
    'las' => 'number',
    'lbr' => 'number',
    'lbs' => 'number',
    'lccfc' => 'null',
    'lccfi' => 'number',
    'lcctc' => 'null',
    'lch' => 'number',
    'ldb' => 'boolean',
    'led' => 'object',
    'ledo' => 'null',
    'lfspt' => 'number',
    'llr' => 'number',
    'lmo' => 'number',
    'lmsc' => 'number',
    'loa' => 'number',
    'loc' => 'string',
    'loe' => 'boolean',
    'lof' => 'number',
    'log' => 'string',
    'loi' => 'boolean',
    'lom' => 'null',
    'lop' => 'number',
    'lopr' => 'boolean',
    'los' => 'string',
    'lot' => 'object',
    'loty' => 'number',
    'lpc' => 'null',
    'lps' => 'number',
    'lpsc' => 'null',
    'lrc' => 'null',
    'lri' => 'null',
    'lrr' => 'null',
    'lse' => 'boolean',
    'lssfc' => 'null',
    'lsstc' => 'null',
    'lto' => 'number',
    'lwf' => 'null',
    'maca' => 'string',
    'mace' => 'string',
    'macp' => 'string',
    'macs' => 'string',
    'map' => 'array',
    'mca' => 'number',
    'mci' => 'number',
    'mcpd' => 'number',
    'mcpea' => 'null',
    'men' => 'boolean',
    'mnt' => 'boolean',
    'modelStatus' => 'number',
    'mptwt' => 'number',
    'mpwst' => 'number',
    'mro' => 'number',
    'msb' => 'boolean',
    'msca' => 'number',
    'mscs' => 'number',
    'msi' => 'number',
    'msr' => 'boolean',
    'mstr' => 'null',
    'mstw' => 'null',
    'mwo' => 'number',
    'nif' => 'string',
    'nld' => 'number',
    'nmo' => 'boolean',
    'npd' => 'boolean',
    'nrg' => 'array',
    'obm' => 'string',
    'oca' => 'null',
    'ocl' => 'number',
    'ocm' => 'string',
    'ocp' => 'number',
    'ocppa' => 'boolean',
    'ocppaa' => 'number',
    'ocppai' => 'number',
    'ocppao' => 'boolean',
    'ocppc' => 'boolean',
    'ocppca' => 'number',
    'ocppcc' => 'boolean',
    'ocppck' => 'boolean',
    'ocppcm' => 'number',
    'ocppcn' => 'boolean',
    'ocppcs' => 'number',
    'ocppd' => 'string',
    'ocppdp' => 'null',
    'ocppe' => 'boolean',
    'ocppf' => 'null',
    'ocppfai' => 'number',
    'ocppfao' => 'boolean',
    'ocppfcm' => 'number',
    'ocppfcn' => 'boolean',
    'ocppfd' => 'string',
    'ocppfe' => 'boolean',
    'ocppff' => 'null',
    'ocppfft' => 'number',
    'ocppfh' => 'number',
    'ocppfla' => 'boolean',
    'ocppflo' => 'boolean',
    'ocppfr' => 'boolean',
    'ocppfss' => 'boolean',
    'ocppft' => 'number',
    'ocppfu' => 'string',
    'ocppg' => 'boolean',
    'ocpph' => 'number',
    'ocppi' => 'number',
    'ocppio' => 'boolean',
    'ocppla' => 'boolean',
    'ocpple' => 'null',
    'ocpplea' => 'null',
    'ocpplo' => 'boolean',
    'ocppmp' => 'null',
    'ocppr' => 'boolean',
    'ocpprl' => 'boolean',
    'ocpprv' => 'number',
    'ocpps' => 'boolean',
    'ocppsc' => 'boolean',
    'ocppss' => 'boolean',
    'ocppt' => 'boolean',
    'ocppte' => 'null',
    'ocpptf' => 'boolean',
    'ocppti' => 'null',
    'ocpptp' => 'null',
    'ocpptt' => 'string',
    'ocppu' => 'string',
    'ocs' => 'number',
    'ocu' => 'array',
    'ocuca' => 'boolean',
    'ocugc' => 'boolean',
    'oem' => 'string',
    'onv' => 'string',
    'opad' => 'null',
    'orsch' => 'boolean',
    'otaif' => 'string',
    'otap' => 'object',
    'pass' => 'boolean',
    'pdi' => 'boolean',
    'pdle' => 'boolean',
    'pdlo' => 'number',
    'pdls' => 'number',
    'pdt' => 'number',
    'pdte' => 'boolean',
    'pen' => 'boolean',
    'pgr' => 'boolean',
    'pha' => 'array',
    'pnp' => 'number',
    'po' => 'number',
    'proto' => 'number',
    'psh' => 'number',
    'psm' => 'number',
    'psmd' => 'number',
    'pvopt_averagePAkku' => 'number',
    'pvopt_averagePGrid' => 'number',
    'pvopt_averagePOhmpilot' => 'number',
    'pvopt_averagePPv' => 'number',
    'pvopt_deltaA' => 'number',
    'pvopt_deltaP' => 'number',
    'pvopt_specialCase' => 'number',
    'pwm' => 'number',
    'qsw' => 'number',
    'rbc' => 'number',
    'rbt' => 'number',
    'rcd' => 'null',
    'rdbf' => 'number',
    'rdbfe' => 'null',
    'rdbs' => 'number',
    'rdbse' => 'null',
    'rde' => 'boolean',
    'rdef' => 'number',
    'rdefe' => 'null',
    'rdes' => 'number',
    'rdese' => 'null',
    'rdpl' => 'number',
    'rdple' => 'null',
    'rdre' => 'number',
    'rdree' => 'null',
    'rfe' => 'null',
    'rfide' => 'boolean',
    'rial' => 'boolean',
    'rill' => 'boolean',
    'riml' => 'boolean',
    'risl' => 'boolean',
    'riul' => 'boolean',
    'rmaf' => 'number',
    'rmav' => 'number',
    'rmdns' => 'boolean',
    'rmif' => 'number',
    'rmiv' => 'number',
    'rsa' => 'null',
    'rsre' => 'boolean',
    'rsrr' => 'number',
    'rssi' => 'null',
    'sau' => 'boolean',
    'sbc' => 'number',
    'sbs' => 'number',
    'scaa' => 'number',
    'scan' => 'array',
    'scas' => 'number',
    'sch_satur' => 'object',
    'sch_sund' => 'object',
    'sch_week' => 'object',
    'scrp' => 'null',
    'sh' => 'number',
    'shrm' => 'boolean',
    'shut' => 'boolean',
    'sic' => 'boolean',
    'sica' => 'null',
    'sid' => 'boolean',
    'sie' => 'boolean',
    'sil' => 'null',
    'sila' => 'null',
    'simo' => 'boolean',
    'sis' => 'boolean',
    'smd' => 'object',
    'smic' => 'boolean',
    'smif' => 'boolean',
    'smjh' => 'boolean',
    'smmp' => 'string',
    'smmr' => 'number',
    'smms' => 'string',
    'smr' => 'boolean',
    'smrm' => 'boolean',
    'sock' => 'boolean',
    'spl3' => 'number',
    'sqrm' => 'boolean',
    'sse' => 'string',
    'stao' => 'null',
    'styp' => 'string',
    'su' => 'boolean',
    'sua' => 'boolean',
    'sumd' => 'number',
    'swc' => 'boolean',
    'tab' => 'number',
    'tcl' => 'null',
    'tds' => 'number',
    'ten' => 'boolean',
    'tma' => 'array',
    'tof' => 'number',
    'tou' => 'number',
    'tpa' => 'number',
    'tpck' => 'array',
    'tpcm' => 'array',
    'trx' => 'null',
    'tsi' => 'null',
    'typ' => 'string',
    'tzt' => 'string',
    'ufa' => 'number',
    'ufe' => 'boolean',
    'ufm' => 'number',
    'ufs' => 'number',
    'ula' => 'number',
    'ule' => 'boolean',
    'ulu' => 'boolean',
    'utc' => 'string',
    'uve' => 'boolean',
    'uvs' => 'number',
    'uvt' => 'number',
    'var' => 'number',
    'waap' => 'number',
    'wae' => 'boolean',
    'wak' => 'boolean',
    'wan' => 'string',
    'wapc' => 'number',
    'wb' => 'null',
    'wbw' => 'number',
    'wcch' => 'number',
    'wccw' => 'number',
    'wda' => 'boolean',
    'wen' => 'boolean',
    'wg' => 'number',
    'wh' => 'number',
    'wh_mid' => 'number',
    'whb' => 'number',
    'whg' => 'number',
    'who' => 'number',
    'whs' => 'number',
    'wifis' => 'array',
    'wo' => 'number',
    'wpk' => 'boolean',
    'ws' => 'number',
    'wsa' => 'boolean',
    'wsc' => 'number',
    'wsh' => 'boolean',
    'wsi' => 'number',
    'wsk' => 'boolean',
    'wsl' => 'null',
    'wsma' => 'number',
    'wsmi' => 'number',
    'wsmr' => 'number',
    'wsms' => 'number',
    'wspc' => 'boolean',
    'wspr' => 'boolean',
    'wssc' => 'number',
    'wst' => 'number',
    'wsw' => 'boolean',
    'wswd' => 'number',
    'zfo' => 'number',
);

is(scalar(keys %{$data->{status}}), 558, 'fixture has exactly 558 direct status fields');
is_deeply([sort keys %{$data->{status}}], [sort keys %expected_type],
    'fixture has the complete expected observed key set');

sub json_type {
    my ($value) = @_;
    return 'null' unless defined $value;
    return 'array' if ref($value) eq 'ARRAY';
    return 'object' if ref($value) eq 'HASH';
    return 'boolean' if JSON::is_bool($value);
    my $copy = $value;
    my $flags = svref_2object(\$copy)->FLAGS;
    return 'number' if $flags & (SVp_IOK | SVp_NOK);
    return 'string';
}

for my $key (sort keys %expected_type) {
    is(json_type($data->{status}{$key}), $expected_type{$key}, "observed JSON type for $key");
}

my @array_shape = (
    ['awpl.marketprice', 14, []],
    ['cc4ae', 4, []],
    ['cc4ap', 4, []],
    ['cc4fm', 4, []],
    ['cc4pm', 4, []],
    ['cc4rc', 4, []],
    ['cc4re', 4, []],
    ['cc4rp', 4, []],
    ['cc4rv', 4, []],
    ['cce.ipv6', 1, []],
    ['clp', 5, []],
    ['dns.resolv', 6, []],
    ['fuzz', 0, []],
    ['led.ranges', 1, []],
    ['led.ranges[0].colors0', 1, []],
    ['led.ranges[0].colors1', 1, []],
    ['map', 3, []],
    ['nrg', 16, []],
    ['ocu', 1, []],
    ['pha', 6, []],
    ['scan', 1, []],
    ['scan[0].f', 10, []],
    ['sch_satur.ranges', 2, []],
    ['sch_sund.ranges', 2, []],
    ['sch_week.ranges', 2, []],
    ['tma', 6, [0, 1]],
    ['tpck', 26, []],
    ['tpcm', 26, []],
    ['wifis', 10, []],
);

sub value_at_path {
    my ($root_value, $path) = @_;
    my $value = $root_value;
    while ($path =~ /(?:\A|\.)([A-Za-z0-9_]+)|\[(\d+)\]/g) {
        $value = defined($1) ? $value->{$1} : $value->[$2];
    }
    return $value;
}

for my $shape (@array_shape) {
    my ($path, $length, $expected_nulls) = @$shape;
    my $array = value_at_path($data->{status}, $path);
    is(ref($array), 'ARRAY', "$path remains an array");
    is(scalar(@$array), $length, "$path retains its observed length");
    my @nulls = grep { !defined $array->[$_] } 0 .. $#$array;
    is_deeply(\@nulls, $expected_nulls, "$path retains observed null positions");
}
is_deeply($data->{status}{nrg}, [230.0,230.1,229.9,0.0,0,0,0,0,0,0,0,0,0,0,0,0],
    'nrg retains all 16 observed numeric positions');
is_deeply($data->{status}{pha}, [JSON::false,JSON::false,JSON::false,JSON::true,JSON::true,JSON::true],
    'phase-status booleans retain their observed positions');

sub privacy_issues {
    my ($text) = @_;
    my @issues;
    push @issues, 'private IPv4' if $text =~ /\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3})\b/;
    while ($text =~ /\b([0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5})\b/g) {
        my $mac = $1;
        my @octets = map { hex($_) } split /:/, $mac;
        push @issues, 'real MAC' if grep($_ != 0, @octets) && !($octets[0] & 0x02);
    }
    push @issues, 'SSID' if $text =~ /"ssid"\s*:\s*"(?!-|")/;
    push @issues, 'token or key' if $text =~ /(?:eyJ[A-Za-z0-9_-]{10,}\.|"token\d*"\s*:\s*"[^<"]|"(?:gmk|cak|faccak|ipw)"\s*:\s*".+")/i;
    push @issues, 'private hostname' if $text =~ /"host(?:name)?"\s*:\s*"(?!Wattpilot-10000001")[^"]+"/i;
    push @issues, 'local OCPP endpoint' if $text =~ /"ocppu"\s*:\s*"ws:\/\/(?!192\.0\.2\.36:18180\/steve\/websocket\/CentralSystemService\/10000001)/i;
    push @issues, 'installation identifier' if $text =~ /"sse"\s*:\s*"(?!10000001")[^"]+"/i;
    return @issues;
}

is_deeply([privacy_issues($bytes)], [], 'fixture contains no detected private or installation-specific values');
ok(scalar privacy_issues('"ip":"192.168.1.9"'), 'negative control detects private IPv4');
ok(scalar privacy_issues('"mac":"00:11:22:33:44:55"'), 'negative control detects a globally administered real MAC');
ok(scalar privacy_issues('"ssid":"PrivateWifi"'), 'negative control detects an SSID');
ok(scalar privacy_issues('"token":"secret-token"'), 'negative control detects token material');
ok(scalar privacy_issues('"host":"private-host"'), 'negative control detects a private hostname');
ok(scalar privacy_issues('"ocppu":"ws://192.168.1.20/ocpp"'), 'negative control detects a local OCPP endpoint');
ok(scalar privacy_issues('"sse":"87654321"'), 'negative control detects an unexpected serial');

is($data->{status}{sse}, '10000001', 'fixture uses the documentation serial');
is($data->{status}{cci}{id}, '<INVERTER_ID>', 'inverter identifier is visibly sanitized');
is($data->{status}{cci}{label}, '<PV_SYSTEM_LABEL>', 'PV-system label is visibly sanitized');
is($data->{status}{ct}, '<VEHICLE_TYPE>', 'vehicle type is visibly sanitized');
like($data->{status}{data}, qr/<REDACTED_TOKEN>/, 'signed data URL contains a visible token placeholder');
like($data->{status}{dll}, qr/<REDACTED_TOKEN>/, 'download URL contains a visible token placeholder');

my $fixture_readme = File::Spec->catfile($root, 't', 'fixtures', 'README.md');
open my $mark_fh, '<:encoding(UTF-8)', $fixture_readme or die "Cannot read $fixture_readme: $!";
my $marking = do { local $/; <$mark_fh> };
close $mark_fh;
like($marking, qr/fullStatus-flex-observed\.json.*sanitized empirical observation/s,
    'fixture is explicitly identified as sanitized empirical observation');

my $protocol_doc = File::Spec->catfile($root, 'docs', 'WATTPILOT-FLEX-JSON-API.md');
open my $doc_fh, '<:encoding(UTF-8)', $protocol_doc or die "Cannot read $protocol_doc: $!";
my $documentation = do { local $/; <$doc_fh> };
close $doc_fh;
my @documented_keys = $documentation =~ /^\| `([^`]+)` \| (?:null|array|object|boolean|number|string) \|/gm;
is(scalar(@documented_keys), 558, 'protocol field table contains exactly 558 rows');
is_deeply([sort @documented_keys], [sort keys %expected_type],
    'protocol field table and observed fixture have the same complete key set');

done_testing;
